name = "AlgebraOfInference"
uuid = "50322c53-2a43-4ee4-bab1-bd226f44c706"
version = "1.0.0-DEV"
authors = ["yl4070 <yl4070@rit.edu> and contributors"]

[workspace]
projects = ["docs"]

[deps]
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
HypothesisTests = "0.11.6"
Reexport = "1.2.2"
StatsModels = "0.7.8"
Tables = "1.12.1"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
